### PR TITLE
Adding link to offiicial documentation

### PR DESCRIPTION
**Pull request by justinmares**

### CODE REVIEW

**Comment by mostlyjason** [comment]
I think this library has been deprecated. The docs now describe how to use either syslog or Monolog. Each doc page should have a link to the latest library on GitHub.

**Comment by justinmares** [comment]
Can you fix?

**Comment by mostlyjason** [comment]
No way to fix it since this library is deprecated. Perhaps we can update the monolog library instead?

Thanks,
Jason

**Comment by justinmares** [comment]
Awesome, mind doing? I'm not sure exactly which library you want updated.

On Mon, Feb 23, 2015 at 12:36 PM, Jason Skowronski <notifications@github.com

**Comment by mostlyjason** [comment]
I'll have our contractors do it in an upcoming sprint.

Thanks,
Jason

**Pull request closed without merging**
